apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argoapphelm1
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    helm:
      releaseName: testhelm
      valueFiles:
        - custom_values_for_argo_helm.yaml
    repoURL: https://github.com/anand1501/argocd_training_code.git
    path: argocd-helm-chart/testchart
    targetRevision: master

