apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocdapp
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    directory:
      recurse: true
      #exclude: "deploy.yaml"
    repoURL: https://github.com/anand1501/argocd_training_code.git
    path: dev
    targetRevision: master

